<!doctype html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <?= $this->tag->stylesheetLink('statics/bootstrap/bootstrap.css'); ?>
    <?= $this->tag->stylesheetLink('statics/sweetalert/sweetalert.css'); ?>
    <title>翻译</title>
    <style>
        p.help-block {
            padding-top: 8px;
            word-spacing: 3px;
        }
        .form-group {
            max-width: 960px;
        }
        div.col-md-8 {
            height: 800px;
            overflow-y: scroll;
        }
        #list .selected {
            box-sizing: border-box;
            border-left: 4px solid #F8BB86;
            font-weight: bolder;
        }
        .danger td {
            text-decoration: line-through;
        }
        body>.row {
            position: relative;
        }
        .translate .team {
            background-repeat: no-repeat;
            background-size: 36px;
            background-position: 80% 50%;
        }
    </style>
</head>
<body class="container-fluid">
<ul id="msg-tabs" class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#injuries" id="injuries-tab" role="tab" data-toggle="tab" aria-controls="injuries" aria-expanded="false">实时消息 <span class="badge"><?= count($injuries) ?></span></a></li>
    <li role="presentation" class=""><a href="#invalid" role="tab" id="invalid-tab" data-toggle="tab" aria-controls="invalid" aria-expanded="true">已失效 <span class="badge"><?= count($invalid) ?></span></a></li>
</ul>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <div id="myTabContent" class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in" id="injuries" aria-labelledby="injuries-tab">
                <table class="table table-hover table-striped" id="list">
                    <thead>
                    <tr class="info">
                        <th>球员</th>
                        <th>状态</th>
                        <th>摘要</th>
                        <th>伤停</th>
                        <th><?= $this->tag->linkTo(['?date_order=' . intval(!(isset($_GET['date_order'])? $_GET['date_order'] : '0')), '发布时间']) ?></th>
                        <th><?= $this->tag->linkTo(['?create_order=' . intval(!(isset($_GET['create_order'])? $_GET['create_order'] : '0')), '采集时间']) ?></th>
                        <th><?= $this->tag->linkTo(['?show_order=' . intval(!(isset($_GET['show_order'])? $_GET['show_order'] : '0')), '状态']) ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($injuries as $key => $item) {
                        ?>
                        <tr class="translate <?= $item->isShow ? 'active' : 'success' ?>" injuries-id="<?= $item->id ?>" style="cursor: pointer">
                            <td class = "team" style="background-image: url('<?= $item->team->logo ?>')"><?= $item->displayName ?></td>
                            <td class="status_cn"><?= $item->statusCn ?></td>
                            <td class="<?= $item->commentCn ? 'comment_cn' : 'comment' ?>" title="<?= $item->commentCn ?: $item->comment ?>"><?= mb_strimwidth($item->commentCn ?: $item->comment,0,35,'...') ?></td>
                            <td class="injury"><?= $item->injury ?></td>
                            <td><?= (new \DateTime($item->date, new \DateTimeZone('UTC')))->format('m-d') ?></td>
                            <td><?= (new \DateTime($item->createtime, new \DateTimeZone('UTC')))->setTimezone(new \DateTimeZone('PRC'))->format('m-d H:i') ?></td>
                            <td class="isshow"><?= $item->isShow ? '未翻译' : '已翻译' ?></td>
                        </tr>
                        <?php
                    }
                    ?>
                    </tbody>
                </table>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="invalid" aria-labelledby="invalid-tab">

                <table class="table table-hover table-striped" id="list">
                    <thead>
                    <tr class="info">
                        <th>球员</th>
                        <th>状态</th>
                        <th>摘要</th>
                        <th>伤停</th>
                        <th>发布时间</th>
                        <th>采集时间</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($invalid as $key => $item) {
                        ?>
                        <tr class="translate danger" injuries-id="<?= $item->id ?>" style="cursor: pointer">
                            <td class = "team" style="background-image: url('<?= $item->team->logo ?>')"><?= $item->displayName ?></td>
                            <td class="status_cn"><?= $item->statusCn ?></td>
                            <td class="<?= $item->commentCn ? 'comment_cn' : 'comment' ?>"><?= mb_strimwidth($item->commentCn ?: $item->comment,0,35,'...') ?></td>
                            <td class="injury"><?= $item->injury ?></td>
                            <td><?= (new \DateTime($item->date, new \DateTimeZone('UTC')))->format('m-d') ?></td>
                            <td><?= (new \DateTime($item->createtime, new \DateTimeZone('UTC')))->setTimezone(new \DateTimeZone('PRC'))->format('m-d H:i') ?></td>
                        </tr>
                        <?php
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-md-4">

        <div class="panel panel-info">
            <div class="panel-heading" style="height: 38px;">
                <h3 class="panel-title pull-left">翻译</h3>
                <button type="button" id="reset" class="pull-right btn btn-xs btn-warning" style="position: relative;top:-2px;">标记为未翻译</button>
            </div>
            <div class="panel-body">
                <form>

                    <input type="hidden" id="id" class="sr-only">

                    <div class="form-group center-block">
                        <div class="row">
                            <div class="col-md-2 hidden-sm hidden-xs">
                                <label for="displayName" class="form-control-static">球员</label>
                            </div>
                            <div class="col-md-10">
                                <p class="well well-sm">
                                    <span id="displayName"></span>
                                    (<span id="displayNameEn" class="text-muted"></span>)
                                </p>
                            </div>
                        </div>
                        <hr>
                    </div>

                    <div class="form-group center-block">
                        <div class="row">
                            <div class="col-md-2 hidden-sm hidden-xs">
                                <label for="dateCN" class="form-control-static">日期</label>
                            </div>
                            <div class="col-md-10">
                                <p class="well well-sm">
                                    <span id="dateCn"></span>
                                    (<span id="date" class="text-muted"></span>)
                                </p>
                            </div>
                        </div>
                        <hr>
                    </div>

                    <div class="form-group center-block">
                        <div class="row">
                            <div class="col-md-2 hidden-sm hidden-xs">
                                <label for="statusCn" class="form-control-static">状态</label>
                            </div>
                            <div class="col-md-10">
                                <input type="text" name="statusCn" id="statusCn" placeholder="状态" class="form-control">
                                <p id="status" class="help-block">　</p>
                            </div>
                        </div>
                        <hr>
                    </div>

                    <div class="form-group center-block">
                        <div class="row">
                            <div class="col-md-2 hidden-sm hidden-xs">
                                <label for="injury" class="form-control-static">伤停部位</label>
                            </div>
                            <div class="col-md-10">
                                <input type="text" name="injury" id="injury" placeholder="伤停部位" class="form-control">
                            </div>
                        </div>
                        <hr>
                    </div>

                    <div class="form-group center-block">
                        <div class="row">
                            <div class="col-md-2 hidden-sm hidden-xs">
                                <label for="commentCn" class="form-control-static">评论</label>
                            </div>
                            <div class="col-md-10">
                                <textarea name="commentCn" id="commentCn" rows="8" placeholder="评论" class="form-control"></textarea>
                                <p id="comment" class="help-block">　</p>
                            </div>
                        </div>
                        <hr>
                    </div>

                    <div class="form-group center-block">
                        <div class="row">
                            <div class="col-md-offset-1 col-md-11">
                                <button type="button" id="update" class="btn btn-primary center-block btn-block">提交</button>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>

    </div>
</div>

<?= $this->tag->javascriptInclude('statics/jquery/jquery.min.js');?>
<?= $this->tag->javascriptInclude('statics/bootstrap/bootstrap.min.js');?>
<?= $this->tag->javascriptInclude('statics/sweetalert/sweetalert.min.js');?>

<!--suppress JSAnnotator -->
<script>
    $(function () {

        var show = function (func, id) {
            id = Number(id) ? Number(id) : 0;
            $.get('api/show/' + id, function (data) {
                for (key in data) {
                    func($('#' + key), data[key]);
                }
                $("#list .selected").removeClass('selected');
                $(".translate[injuries-id='" + data['id'] + "']").addClass('selected');
            }, "json");
        };

        var setTableSuccess = function (id, status_cn, injury, comment_cn) {
            var tr = $(".translate[injuries-id='" + id + "']");
            if (!tr.hasClass('danger')) {
                tr.removeClass('active');
                tr.addClass('success');
            }
            tr.find('.isshow').text('已翻译');
            tr.find('.status_cn').text(status_cn);
            tr.find('.injury').text(injury);
            var td = tr.find('.comment, .comment_cn');
            td.attr('title', comment_cn);
            if (comment_cn.length > 20) {
                comment_cn = comment_cn.substr(0, 20) + '...';
            }
            td.text(comment_cn);
        };

        show(function (obj, value) {
            obj.text(value);
            obj.val(value);
        }, $('.translate:first').attr('injuries-id'));

        $('#update').on('click', function () {
            var that = this;
            $(this).attr("disabled", "true");
            var id = $('#id').val();
            var status_cn = $('#statusCn').val();
            var injury = $('#injury').val();
            var comment_cn = $('#commentCn').val();
            $.post('api/update/' + id, {
                statusCn: status_cn,
                injury: injury,
                commentCn: comment_cn
            }, function (data) {
                if (data.status === 'success') {
                    setTableSuccess(id, status_cn, injury, comment_cn);
                    sweetAlert({
                        type: "success",
                        title: "提交成功!",
                        text: "即将进入下一题。",
                        timer: 1000,
                        showConfirmButton: false
                    });
                    show(function (obj, value) {
                        obj.animate({opacity: 0}, function () {
                            obj.text(value);
                            obj.val(value);
                            obj.animate({opacity: 1});
                        });
                    });
                } else {
                    sweetAlert({
                        type: "error",
                        title: "提交失败!",
                        text: data.data,
                        timer: 5000,
                        showConfirmButton: true
                    });
                }
                $(that).removeAttr("disabled");
            }, "json");
        });

        $('#reset').on('click', function () {
            var that = this;
            $(this).attr("disabled", "true");
            var id = $('#id').val();
            $.get('api/reset/' + id, function (data) {
                if (data.status === 'success') {
                    var tr = $(".translate[injuries-id='" + id + "']");
                    if (!tr.hasClass('danger')) {
                        tr.removeClass('success');
                        tr.addClass('active');
                    }
                    tr.find('.isshow').text('未翻译');
                    sweetAlert({
                        type: "success",
                        title: "标记成功!",
                        timer: 1000,
                        showConfirmButton: false
                    });
                } else {
                    sweetAlert({
                        type: "error",
                        title: "提交失败!",
                        text: data.data,
                        timer: 5000,
                        showConfirmButton: true
                    });
                }
                $(that).removeAttr("disabled");
            }, 'json');

        });
        
        $('.translate').on('click', function () {
            show(function (obj, value) {
                obj.animate({opacity: 0}, function () {
                    obj.text(value);
                    obj.val(value);
                    obj.animate({opacity: 1});
                });
            }, $(this).attr('injuries-id'));
        });

        $('#msg-tabs a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');
        });
    });
</script>
</body>
</html>